trigger: 
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: kesavakiran/devops-mini-project3


stages:
- stage: BuildAndPush
  displayName: Build And Push Docker Image
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: Building Docker Image
      inputs:
        command: build
        Dockerfile: '**/Dockerfile'
        tags: |
          $(imageName):latest

    - task: Docker@2
      displayName: push the docker Image
      inputs:
        command: push
        tags: |
          $(imageName):latest
    
